lab3/Formularz/Models/Dane.cs
using System.ComponentModel.DataAnnotations;

namespace Formularz.Models
{
    public class Dane
    {
        [Required(ErrorMessage = "Prosze podaj Imie")]
        [MinLength(2, ErrorMessage = "Imie musi miec przynajmniej 2 znaki")]
        public string Imie { get; set; }

        [Required(ErrorMessage = "Prosze podaj Nazwisko")]
        [MinLength(2, ErrorMessage = "Nazwisko musi miec przynajmniej 2 znaki")]
        public string Nazwisko { get; set; }

        [Required(ErrorMessage = "Prosze podaj Email")]
        [EmailAddress(ErrorMessage = "Niepoprawny format Email")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Prosze podaj Haslo")]
        [DataType(DataType.Password)]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$", ErrorMessage = "Haslo musi miec min 8 znakow, zawierac min jedna duza litere, jedna mala litere i jedna cyfre")]
        public string Haslo { get; set; }

        [Required(ErrorMessage = "Prosze potwierdz Haslo")]
        [Compare("Haslo", ErrorMessage = "Hasla musza byc takie same")]
        public string PotwierdzHaslo { get; set; }

        [Phone(ErrorMessage = "Niepoprawny format Nr Telefonu")]
        public string? NrTelefonu { get; set; }

        [Range(10, 80, ErrorMessage = "Wiek musi byc pomiedzy 10 a 80")]
        public int? Wiek { get; set; }

        public string? Miasto { get; set; }

    }

    public enum Miasta
    {
        Tarnow = 1,
        Krakow = 2,
        Rzeszow = 3,
        Bochnia = 4,
        Brzesko = 5
    }
}

lab3/Formularz/Models/ErrorViewModel.cs
namespace Formularz.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

lab3/Formularz/Controllers/DaneController.cs
using Formularz.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Formularz.Controllers
{
    public class DaneController : Controller
    {
        // GET: DaneController
        public ActionResult Index()
        {
            return View();
        }

        // GET: DaneController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: DaneController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DaneController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DaneController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DaneController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DaneController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DaneController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public IActionResult Form()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Form(Dane dane)
        {
            if(ModelState.IsValid)
            {
                return View("Wynik", dane);
            }
            return View();
        }
        public IActionResult Wynik(Dane dane)
        {
            return View(dane);
        }
    }
}

lab3/Formularz/Controllers/HomeController.cs
using Formularz.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Formularz.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lab3/Formularz/Views/Dane/Form.cshtml
@model Formularz.Models.Dane;
@{
    ViewData["Title"] = "Form";
}

<form asp-action="Form" method="post">
    <div asp-validation-summary="All"></div>
    <div>
        <label asp-for="Imie" ></label>
        <input type="text" asp-for="Imie" />
    </div>
    <div>
        <label asp-for="Nazwisko"></label>
        <input type="text" asp-for="Nazwisko" />
    </div>
    <div>
        <label asp-for="Email"></label>
        <input type="email" asp-for="Email" />
    </div>
    <div>
        <label asp-for="Haslo"></label>
        <input type="password" asp-for="Haslo" />
    </div>
    <div>
        <label asp-for="PotwierdzHaslo"></label>
        <input type="password" asp-for="PotwierdzHaslo" />
    </div>
    <div>
        <label asp-for="NrTelefonu"></label>
        <input type="tel" asp-for="NrTelefonu" />
    </div>
    <div>
        <label asp-for="Wiek"></label>
        <input type="number" asp-for="Wiek" />
    </div>
    <div>
        <label asp-for="Miasto"></label>
        <select asp-for="Miasto" asp-items="Html.GetEnumSelectList<Miasta>()"></select>
    </div>
    <div>
        <input type="submit" />
        <input type="reset" value="Wyczyść" />
    </div>
</form>

lab3/Formularz/Views/Dane/Wynik.cshtml
@model Formularz.Models.Dane;
@{
    ViewData["Title"] = "Wynik";
}

<h1>"Rejestracja zakończona pomyślnie"</h1>

lab3/Formularz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Formularz</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Formularz.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Formularz</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dane" asp-action="Form">Form</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Formularz - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>